# Get All Employee

GET http://dummy.restapiexample.com/api/v1/employees HTTP/1.1

###

GET http://dummy.restapiexample.com/api/v1/employee/1 HTTP/1.1


# Post Employee
###

POST http://dummy.restapiexample.com/api/v1/create HTTP/1.1
content-type: application/json

{"name":"test12","salary":"1234","age":"25"}

# Do Tomorrow

# Put method , Update Employee Details 
###

PUT http://dummy.restapiexample.com/api/v1/update/23
content-type: application/json

{"name":"test1","salary":"1123","age":"23"}

# Delete Employee 
###

DELETE http://dummy.restapiexample.com/api/v1/delete/2/



